"""add_ai_usage_table

Revision ID: 54199692f393
Revises: d359aca5df8f
Create Date: 2026-09-20 14:17:21.324611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54199692f393'
down_revision: Union[str, Sequence[str], None] = 'd359aca5df8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('estimated_input_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_total_tokens', sa.Integer(), nullable=False),
    sa.Column('provider_input_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_output_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_total_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_conversation_id'), 'ai_usage', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_request_id'), 'ai_usage', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_usage_request_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_conversation_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
